file_help = 'file selection REQUIRED'
where_help = 'filtering in the format "COLUMN_NAME[>/</=]PARAMETER"'
aggregate_help = 'aggregation in the format "COLUMN_NAME=[avg/min/max]"'
where_error = 'filtering by {} cannot be applied to column {}'
aggregate_error = 'cannot execute command {} for column {}'
column_error = 'a column with this name doesn\'t exist'
command_error = 'only the symbols ">", "<", or "=" are allowed for filtering'
aggregate_param_mistake = 'aggregation is possible with the commands "avg", "max", "min"'
no_data = 'no data matching the condition was found'
file_error = 'file not found'
